FROM ubuntu:18.04
LABEL maintainer="YUNHAN" version="1.0"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /tmp
RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    apt-get -y install \
      apache2
RUN git clone https://github.com/KukuruKurobane/firstplan.git && \
    mv ./firstplan/* /var/www/html/ && \
    rm /var/www/html/index.html && \
    chown -R www-data:www-data /var/www/html/
EXPOSE 8000
ENTRYPOINT ["init.sh"]