FROM ubuntu:18.04
LABEL maintainer="YUNHAN" version="1.0"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /tmp

RUN apt-get -y update && \
    apt-get -y install apache2 && \
    apt-get -y install \
      apache2 curl wget git unzip sudo \
      pwgen postfix libcurl4 locales

RUN git clone https://github.com/KukuruKurobane/firstplan.git && \
    rm /var/www/html/index.html && \
    mv ./firstplan/* /var/www/html/

COPY ./foreground.sh /etc/apache2/
ENTRYPOINT ["/etc/apache2/foreground.sh"]